# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

r:
  - release
  - devel
  - oldrel

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install libfftw3-dev ; fi

matrix:
  allow_failures:
    - r: devel
    - r: oldrel
